### ISSUE TITLE
Doesn't work with fresh install from package.json using npm 3

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/install-files#7]
Follow-up to #4. Now, when you install `my-ebextensions` into `my-microservice`

```sh
npm install my-ebextensions --save-dev
```

will work, but afterwards,

```sh
rm -rf node_modules && npm install
```

will break. It will break because, during the latter case, [`fileInstallingPath`](https://github.com/mixmaxhq/install-files/blob/60a96146f85ccd55876a79487f983f9529aace93/src/index.js#L34) is `/path/to/my-microservice/node_modules/my-ebextensions`, so we set [`source`](https://github.com/mixmaxhq/install-files/blob/60a96146f85ccd55876a79487f983f9529aace93/src/index.js#L49) to `/path/to/my-microservice/node_modules/my-ebextensions/node_modules/my-ebextensions/${sourceDir}` whereas it would be totally fine (in that case) to use the passed-in `sourceDir` relative to `my-ebextensions`' root like npm 2 does.

**Comment by wearhere** [comment]
cc @GoGoCarl. This isn't pressing for us @ Mixmax to resolve since we're still using npm 2.15.9 but you might want to take a look

**Comment by GoGoCarl** [comment]
I'm not quite sure I understand but I'll check it out.

**Comment by GoGoCarl** [comment]
@wearhere I may be misunderstanding the scenario.  Here's what I did:

* Create a fresh project using npm v3.9.5 with minimal package.json (name, version, no scripts)
* Add my project that uses `install-files` as a dev dependency
* Run `npm install`, all works as expected
* `rm -rf node_modules`
* `rm -rf my_shared_files` -- to ensure they get regenerated in the next step
* `npm install`

When I ran the second NPM install:
* fileInstallingPackagePath was `/path/to/my-microservice`
* source was `/path/to/my-microservice/node_modules/my-extension/shared`
* target was `/path/to/my-microservice`

While I don't typically `rm -rf node_modules` in my workflow, I haven't had any issues thus far with projects I'm using.  Did I miss a step above?

**Comment by wearhere** [comment]
Ah ok, so the issue here was merely running `npm install`, using npm 3, on an npm-shrinkwrap.json produced using npm 2 (and [`npm-shrinkwrap`](https://github.com/uber/npm-shrinkwrap), for whatever that's worth).

I'm not sure if that's supposed to be supported? The rest of the packages install fine. We probably don't need to support it though. If, after upgrading to npm 3, I do `rm npm-shrinkwrap.json && rm -rf node_modules && npm install` then it works fine. It also works fine if I recreate the shrinkwrap using npm 3 and then do `rm -rf node_modules && npm install`.

Thanks for trying to repro @GoGoCarl!
